require("plugins.coding.typescript-tools")
require("plugins.coding.lsp")
require("plugins.coding.completion")
require("plugins.coding.treesitter")
require("plugins.coding.autopairs")
require("plugins.coding.better-escape")
require("plugins.coding.comment")
require("plugins.coding.conform")
-- require("plugins.coding.marks")
require("plugins.coding.surround")
require("plugins.coding.tailwind-tools")
require("plugins.coding.todo-comments")
require("plugins.coding.ufo")
