require("plugins.ui.web-devicons")
require("plugins.ui.catppuccin")
require("plugins.ui.colorful-winsep")
require("plugins.ui.dashboard")
require("plugins.ui.dressing")
require("plugins.ui.heirline")
require("plugins.ui.image")
require("plugins.ui.indent-blankline")
require("plugins.ui.markview")
require("plugins.ui.neo-tree")
require("plugins.ui.no-neck-pain")
require("plugins.ui.notify") -- must be before noice
require("plugins.ui.noice")
require("plugins.ui.outline")
require("plugins.ui.rainbow-delimiters")
require("plugins.ui.telescope")
require("plugins.ui.time-tracker")
require("plugins.ui.toggleterm")
require("plugins.ui.window-picker")
require("plugins.ui.colorizer") -- recommended to load last
