interface = "wlan0"
long_uptime = true
long_shell = false
long_kernel = false
current_shell = true
physical_cores = true
theme = "Hydrogen"
show = [
	"Host",
  "Kernel",
	"Distribution",
	"DesktopEnvironment",
	"Terminal",
	"Shell",
	"Uptime",
	"Resolution",
]
