require("plugins.ui.web-devicons")
require("plugins.ui.bufferline")
require("plugins.ui.catppuccin")
require("plugins.ui.dashboard")
require("plugins.ui.dressing")
require("plugins.ui.heirline")
require("plugins.ui.indent-blankline")
-- require("plugins.ui.lualine")
require("plugins.ui.neo-tree")
require("plugins.ui.noice")
require("plugins.ui.rainbow-delimiters")
require("plugins.ui.telescope")
require("plugins.ui.toggleterm")
require("plugins.ui.window-picker")
require("plugins.ui.colorizer") -- recommended to load last
