require("plugins.web-devicons")
require("plugins.neorg")
require("plugins.colorful-winsep")
require("plugins.lualine")
require("plugins.render-markdown")
require("plugins.lsp")
require("plugins.typescript-tools")
require("plugins.tailwind-tools")
require("plugins.ufo")
require("plugins.yazi")
require("plugins.gen")
require("plugins.indent-blankline")
require("plugins.telescope")
-- require("plugins.incline")
-- require("plugins.winbar")
